import fs from 'node:fs/promises';import {TITLE,CATS,CHAINS,CFG,CHAPTERS,INTRO,TASKS,DAILY,needMass} from '../src/data.mjs';
const write=(name,s)=>fs.writeFile(new URL('../docs/'+name,import.meta.url),s);
let story=`# 角色、世界观与完整剧情\n\n## 新作世界观\n布布和一二一起整理巷子尽头的一间旧屋：旧家具和纸箱还在，需要擦洗、修补、安放。两只决定把它变成能喝茶、画画、种花、读书和邀请人来坐坐的地方。此为本游戏原创支线，并非对用户此前电影剧本的替代或正史续写。\n\n## 人设\n布布温和、可靠、略憨；通过具体行动照顾一二，不突然变成粗鲁霸道角色。一二活泼、好奇、有想象力，也能细心回应布布，不只是闯祸。称呼自然使用“一二宝”“臭布布”。两只体型近似、外形以用户设定图为准，无新增永久服装。\n\n## 开场四幕\n`;
for(const [i,l]of INTRO.entries())story+=`\n### ${i+1}. ${l.title}\n场景：${l.aside}\n\n${l.who==='bubu'?'布布':'一二'}：${l.text}\n`;
for(const [i,c]of CHAPTERS.entries()){
 story+=`\n## 第${i+1}章：${c.name}\n${c.sub}\n`;
 for(const t of TASKS.filter(t=>t.chapter===i)){
  story+=`\n### 心愿${String(t.id+1).padStart(2,'0')}：${t.name}\n${t.who==='bubu'?'布布':'一二'}的准备请求：${t.wish}\n\n需求：${t.needs.map(r=>`${CHAINS[r.c].items[r.l-1]}（${r.l}级）×${r.n}`).join('、')}。交付得到1心愿星、${t.coins}金币、${t.energy}体力。布置消耗这1颗心愿星。\n\n`;
  for(const[who,pose,text]of t.after)story+=`${who==='bubu'?'布布':'一二'}：${text}\n\n`;
 }
 story+=`### 本章回忆：${c.memory}\n${c.text}\n`;
}
story+='\n## 完整结尾与通关后\n第24次布置后出现完整告别页，保存已完成状态。随后仍可做邻里委托、升级工作台、补全图鉴、换色、拍照和重读所有已完成对白。不强制开新周目，不清空家具。\n';await write('03_角色世界观与完整剧情.md',story);
const sumCoins=TASKS.reduce((n,t)=>n+t.coins,0),sumEnergy=TASKS.reduce((n,t)=>n+t.energy,0),sumMass=TASKS.reduce((n,t)=>n+needMass(t.needs),0);
let balance=`# 数值与状态闭环（以代码为准）\n\n## 经济一览\n|资源|来源|消耗/上限|零资源时的恢复|\n|---|---|---|---|\n|体力|初始100；主线每单2至4；邻里订单；升级每级${CFG.levelEnergy}；每章${CFG.chapterEnergy}；每日礼物${CFG.dailyGiftEnergy}|产出每次1；自然恢复到100；奖励可暂存超过100|每15秒恢复1；每分钟免费茶歇+30；随身点心；可选轻松模式|\n|金币|初始120；主线/邻里交付；升级20；尘封+5；每日；出售|升级生产器、仓库、剪刀、点心和补给|生产与主线布置不耗金币；邻里订单与出售持续提供金币|\n|心愿星|当前主线交付固定1颗|当前布置消耗1；与交付许可绑定|不能在商店花掉，不能因乱花金币卡主线|\n|工作台库存|自然每6秒+1；升级立即补满|容量18/24/30；正常产出耗1|时间恢复、升级、轻松模式|\n|剪刀|初始3；每日礼物1；每章1；金币购买|拆分一次耗1，需额外空格|普通重新产出永远可用；拆分非主线必要条件|\n\n## 可推导总量\n24张主线需求的基础物品价值总和为 **${sumMass}**；固定主线金币合计 **${sumCoins}**；固定主线体力合计 **${sumEnergy}**；心愿星共发出24、对应消耗24。此处不含初始尘封、章节材料、掉落的二阶物品、升级、每日和自然恢复，因此不等同于所需点击次数。\n\n生产器等级1/2/3产出二阶物品的概率为20%/32%/44%，其余产出一阶；单次基础价值期望为1.20/1.32/1.44。每条链只产本类，不掺入不可预知的跨类稀有副产物。教程首次补货固定一阶。\n\n## 花费\n工作台1→2：140金币；2→3：400金币。\n仓库每次扩4格，费用80、160、240、320，最终24格。\n点心60金币（使用+30体力）；剪刀45金币；心愿补给包65金币（当前主线来源的三件一阶与一件二阶，放进待领队列）。\n免费茶歇每60秒+30体力。工作台升级和全部商店道具都不是主线硬门槛。\n\n## 来源解锁与空间\n|工作台|初次可用心愿|物品链|\n|---|---|---|\n`;
for(const c of CATS)balance+=`|${CHAINS[c].producer}|第${CHAINS[c].unlock+1}项（已布置${CHAINS[c].unlock}处）|${CHAINS[c].items.join(' → ')}|\n`;
balance+='\n下两行纸箱每组两格，在第2、4、6、8、10、12、14处布置后腾出；不收费、不随机。49格减6个固定工作台，全部解开后最多43个可移动物品格，另有8至24仓库格与独立待领队列。\n\n## 状态闭环\n`当前阶段且未交付 → 检查全部需求 → 一次性扣物 → 当前交付许可=true，心愿星=1 → 选配色并布置 → 心愿星=0，许可=false，阶段+1 → 解锁来源/空间/回忆 → 下一愿望`。\n\n旁支只给金币、体力和经验，不发主线许可。最高阶无法继续合成。非同类物品交换；尘封不能被当成普通免费库存。满仓、满盘、冷却、金币不足等失败不会先收费。\n\n## 数值审阅后的修改\n初版的体力奖励叠加过大，正常主线结束可堆到六百多点，使体力失去意义。正式版改为：主线2至4、章节10、等级5、每日礼物20、每日目标8/10/8；不改变免费恢复、点心和轻松模式的救济路径。详情与最终100种子结果见测试文档。\n\n## 没有被证明的部分\n通关可达性不等于商业留存。没有真实玩家的时长、D1/D7留存、付费率或“必然受欢迎”结论。设计目标是让第一轮故事在一个可完成的中短时单机体验中闭合；具体节奏还应由真人试玩校准。\n';
await write('04_数值与状态闭环.md',balance);
const ui=JSON.parse(await fs.readFile(new URL('../qa/browser-report.json',import.meta.url),'utf8')),sim=JSON.parse(await fs.readFile(new URL('../qa/simulation-summary.json',import.meta.url),'utf8'));
let qa=`# 测试报告与审阅修订\n\n## 最终结果\n|验证层|结果|证据|\n|---|---|---|\n|纯规则单元测试|37/37通过|qa/unit-tests.tap|\n|正常模式合法操作主线模拟|${sim.passed}/${sim.campaigns}随机种子通关24项|qa/simulation-summary.json|\n|全部图鉴与轻松模式|36/36发现，24/24修缮|qa/campaign-full.json、simulation-summary.json|\n|Chromium界面回归|${ui.passed}/${ui.total}通过，0未捕获JS异常|qa/browser-report.json|\n|素材与角色检查|36个物品、全部角色/任务素材存在；头像与全身分用途复核|qa/*contact-sheet.jpg、art/manifest.json|\n\n100个正常模式种子的主线产出次数范围：${sim.standard.minProduce}至${sim.standard.maxProduce}。最终最低体力：${sim.standard.minFinalEnergy}。模拟使用正常公开动作和虚拟时钟，不注入资源；等待秒数仅用于可达性，不是对真人时长的测量。\n\n## 发现并修复的问题\n|问题|修复|回归证据|\n|---|---|---|\n|单文件模板注入误处理代码中的$$，导致脚本变量重复|用替换函数而非替换字符串内嵌脚本|构建字符串测试与浏览器启动通过|\n|一二45度裁切过窄，白色脸部被背景洪水填充误删|扩大完整闭合轮廓的裁切范围；重新审阅所有角色|最终角色审阅页、启动页与剧情截图|\n|半身表情可能作为全身演员显示|场景/对话映射到参考图里的完整动作；半身保留为头像|家园、开场和晚间截图|\n|新手提示放在棋盘后，可能被底部检查栏遮住|提示提前至棋盘之前|界面测试验证纵向位置|\n|360×640下普通订单占用过多空间|新增紧凑心愿条与完整委托抽屉；所有7行在教学后可见|紧凑模式实际几何检查与截图|\n|触摸滚动与拖动互相抢手势|普通物品允许拖动；空格/固定格可纵向滚动；pointercancel撤销悬浮态|真实触摸管线和取消手势回归|\n|键盘操作后DOM重绘丢失焦点|键盘激活后恢复格子焦点；增加真实行结构|键盘选择/合成回归|\n|体力奖励过多，主线结束积累六百多点|重新平衡主线、章节、等级与每日回报|重跑37项规则与100种子模拟|\n|拍照画布可能让场景外家具伸入说明区|导出画布按房间边界裁切|实际PNG导出文件|\n|第五章夜间对白与日间场景不同步|进入第5章默认夜景，保留日夜切换|第5章家园与夜景截图|\n\n## 规则测试覆盖\n包括首次完整闭环、来源解锁、合成守恒、尘封、交换、六级上限、生产器保护、满盘不扣资源、零体力/零库存、离线恢复、时间倒退、仓库计数、重复配方、跨仓交付、重复交付/布置、免费刷新、满仓与待领保护、扩容、拆分、撤销奖励一致性、排序、每日幂等、轻松模式、JSON往返与错误输入拒绝。\n\n## 浏览器检查方法与边界\n${ui.method}\n\n实际浏览器：${ui.browser}。视口：360×640、390×844、430×932、1366×900。没有用这些桌面模拟结果冒称真实iOS/Android机型测试。原始状态校验、导出PNG和截图均随包保留。\n\n## 浏览器检查逐项\n`;
for(const c of ui.checks)qa+=`- [${c.passed?'x':' '}] ${c.name}${c.detail?' — '+c.detail:''}\n`;
qa+='\n## 发布前仍需由目标环境完成\n真实目标浏览器的文件导航与持久化、真实触控设备、Safari/平台WebView、公网HTTPS与PWA安装缓存、IP授权与平台审核。本次没有账号/云服务/支付服务，这些不属于“已通过”测试项。\n';
await write('06_测试报告与审阅修订.md',qa);
await fs.writeFile(new URL('../qa/economy-report.json',import.meta.url),JSON.stringify({mainBaseValue:sumMass,mainCoins:sumCoins,mainEnergy:sumEnergy,starsEarned:24,starsSpent:24,config:CFG,chains:CHAINS,tasks:TASKS.map(t=>({stage:t.id,name:t.name,needs:t.needs,coins:t.coins,energy:t.energy}))},null,2));
console.log('Generated story, balance, and QA documentation directly from final code/data.');
